# Урок 1

# Линейное пространство. Основные понятия. Часть 1

In [58]:
import numpy as np
from numpy.linalg import norm
from math import acos, pi

## Практическое задание. Часть 1

__1.__ Исследуйте на линейную зависимость:

$$f_{1}(x)=e^{x}, f_{2}(x)=1, f_{3}(x)=x+1, f_{4}(x)=x-e^{x}.$$


__1.__ Решение:

Заметим, что
$$ 1 * (e^{x}) + 1 * (1) + (-1) * (x + 1) + 1 * (x - e^{x}) = 0$$

То есть
$$ 1 * f_{1}(x) + 1 * f_{2}(x) + (-1) *  f_{3}(x) + 1 *  f_{4}(x) = 0$$

Что означает, что функции линейно зависимы.

__2.__ Исследуйте на линейную зависимость:
$$f_{1}(x)=2, f_{2}(x)=x, f_{3}(x)=x^{2}, f_{4}(x)=(x+1)^{2}$$

__2.__ Решение:

Заметим, что
$$ (x + 1)^2 = 1 * x^2 + 2 * x + 0.5 * 2$$

То есть
$$f_{4}(x) = 1 * f_{3}(x) + 2 * f_{2}(x) + 0.5 * f_{1}(x)$$

Что означает, что функции линейно зависимы.


__3.__ Найдите координаты вектора $x = (2, 3, 5)\in \mathbb{R}^{3}$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$.

__3.__ Решение:

Совокупность $n$ линейно независимых векторов линейного пространства $V$ будет называться _базисом_ этого пространства, если для каждого элемента $u$ пространства $V$ найдутся такие вещественные числа $\xi_{1},\xi_{2}. . . , \xi_{n}$, что справедливо равенство:

$$u = \xi_{1}e_{1} + \xi_{2}e_{2} + . . . + \xi_{n}e_{n}.$$

Коэффициенты $\xi_{i}$ в этом выражении называются _координатами_ вектора $u$ в базисе $e_{1}  . . . , e_{n}$, а само такое представление вектора $u$ — _разложением этого вектора по базису_.

$$x = 0.5b_{1} + 1b_{2} + 3b_{3}$$
**Ответ**:  $x = (0.5, 1, 3)$ -  координаты вектора $x = (2, 3, 5)$ в базисе $b_{1}=(0, 0, 10)$, $b_{2}=(2, 0, 0)$, $b_{3}=(0, 1, 0)$


__4.__ Найдите координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

а) в базисе $1$, $x$, $x^{2}$;

б) в базисе $x^{2}$, $x-1$, $1$.

__4.__ Решение. Найдите координаты вектора $3x^{2}-2x+2\in\mathbb{R}^{3}[x]$:

а) в базисе $1$, $x$, $x^{2}$;

$$u = \xi_{1}e_{1} + \xi_{2}e_{2} + . . . + \xi_{n}e_{n}.$$

$$e_{1} = 1$$
$$e_{2} = x$$
$$e_{3} = x^2$$

Разложим данный вектор по базису:
$$3x^{2}-2x+2 = 3 * e_{3} + (-2) * e_{2} + 2* e_{1}.$$
**Ответ**: $(2, -2, 3)$ координаты вектора $3x^{2}-2x+2$ в базисе $1$, $x$, $x^{2}$

б) в базисе $x^{2}$, $x-1$, $1$.

$$u = \xi_{1}e_{1} + \xi_{2}e_{2} + . . . + \xi_{n}e_{n}.$$

$$e_{1} = x^2$$
$$e_{2} = x - 1$$
$$e_{3} = 1$$

Разложим данный вектор по базису:
$$3x^{2}-2x+2 = 3 * e_{1} + (-2) * e_{2} + 0* e_{3}.$$
**Ответ**: $(3, -2, 0)$ координаты вектора $3x^{2}-2x+2$ в базисе $x^{2}$, $x-1$, $1$

__5.__ Установите, считается ли линейным подпространством:

а) совокупность всех векторов трёхмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;
    
б) все векторы, считающиеся линейными комбинациями данных векторов $\{u_{1}, u_{2} \ldots, u_{n}\}$.

__5.__ Решение:

а) совокупность всех векторов трёхмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю;

то есть это ветора типа **(0, y, z) и (x, 0, z)**.

Подмножество $L$ линейного пространства $V$ считается его подпространством только тогда, когда для любых элементов $u, v\in L$ и любого $\alpha \in \mathbb{R}$ выполняются условия:

$$1)\ u+v\in L;$$

$$2)\ \alpha\cdot u \in L.$$

Проверим выполнение этих условий.

1. Сложение

(0, y1, z1) + (x2, 0, z2) = (x2, y1, z1+z2).

Получившийся вектор (x2, y1, z1+z2) уже не входит в группу векторов типа (0, y, z) и (x, 0, z).

2. Умножение

$(0, y_1, z_1) * \alpha  = (0, y_1*\alpha, z_1*\alpha)$

$(x_2, 0, z_2) * \alpha  = (x_2*\alpha, 0, z_2*\alpha)$

Получившиеся вектора входят в группу векторов типа (0, y, z) и (x, 0, z).

**Ответ**: совокупность всех векторов трёхмерного пространства, у которых по крайней мере одна из первых двух координат равна нулю НЕ считается линейным подпространством, так как не выполняется условие замкнутости по сложению.


б) все векторы, считающиеся линейными комбинациями данных векторов $\{u_{1}, u_{2} \ldots, u_{n}\}$.

Да, так как сложение и умножение, относительно которых должно быть замкнуто линейное подпространство, относится к линейным комбинациям над данными векторами.

**Более формальное решение:**

Любой вектор множества можно представить в виде $$\sum_{t=1}^{n}\lambda_{t}u_{t}$$
Сумма двух векторов: $$\sum_{t=1}^{n}\alpha_{t}u_{t} + \sum_{t=1}^{n}\beta_{t}u_{t} = \sum_{t=1}^{n}(\alpha_{t} + \beta_{t})u_{t} =\sum_{t=1}^{n}\lambda_{t}u_{t} $$
Произведение вектора на число: $$\alpha \cdot \sum_{t=1}^{n}\lambda_{t}u_{t} = \sum_{t=1}^{n}\alpha \cdot \lambda_{t}u_{t} = \sum_{t=1}^{n}\beta_{t}u_{t}$$

Т.к. полученные вектора принадлежат указанному множеству, поэтому указанное множество векторов является линейным подпространством.

**Ответ**: все векторы, считающиеся линейными комбинациями данных векторов $\{u_{1}, u_{2} \ldots, u_{n}\}$ считается линейным подпространством.


## Практическое задание. Часть 2.

__1.__ Найдите скалярное произведение векторов $x, y \in \mathbb{R}$:<br>
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>
б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

__1.__ Решение:
а) $x=(0,-3, 6),~y=(-4, 7, 9);$<br>

In [59]:
res = 0 * (-4) + (-3) * 7 + 6 * 9
res

33

In [60]:
x = np.array([0,-3, 6])
x

array([ 0, -3,  6])

In [61]:
y = np.array([-4, 7, 9])
y

array([-4,  7,  9])

In [62]:
np.dot(x, y)

33

б) $x=(7, -4, 0, 1),~y=(-3, 1, 11, 2).$

In [63]:
res_b  = 7 * (-3) + (-4) * 1 + 0 * 11 + 1 * 2
res_b 

-23

In [64]:
x_b = np.array([7, -4, 0, 1])
x_b

array([ 7, -4,  0,  1])

In [65]:
y_b = np.array([-3, 1, 11, 2])
y_b

array([-3,  1, 11,  2])

In [66]:
np.dot(x_b, y_b)

-23

__2.__ Найдите нормы векторов $(4, 2, 4)$ и $(12, 3, 4)$ и угол между ними.

__2.__ Решение:

Найдем эти варианты норм:

- при $p = 1$ получаем $\ell_{1}$ норму — _манхэттенская норма_, или _манхэттенское расстояние_:

$$\left\|x\right\|_{1} = \sum_{i}|x_{i}|;$$

- при $p = 2$ получаем $\ell_{2}$ норму — _евклидова норма_, часто используемая:

$$\left\|x\right\|_{2} = \sqrt{\sum_{i}|x_{i}|^{2}}.$$

Косинус угла будем находить по формуле:

В любом вещественном евклидовом пространстве можно ввести понятие _угла_ между двумя произвольными элементами $x$ и $y$. Углом $\varphi \in [0, \pi]$ между этими элементами назовём угол, косинус которого определяется соотношением:

$$cos\varphi = \frac{(x,y)}{\left \|x\right \|\cdot\left \|y\right \|}.$$

In [67]:
#вручную
#манхэттенское расстояние

norm_x1 = 4 + 2 + 4
norm_x1

10

In [68]:
norm_x2 = 12 + 3 + 4 
norm_x2 

19

In [69]:
#евклидова норма
norm_ev_x1 = np.sqrt(4 ** 2 + 2 ** 2 + 4 ** 2)
norm_ev_x1

6.0

In [70]:
norm_ev_x2 = np.sqrt(12 ** 2 + 3 ** 2 + 4 ** 2)
norm_ev_x2

13.0

In [71]:
#c помощью norm

x1 = np.array([4, 2, 4])

x2 = np.array([12, 3, 4])

x1, x2

(array([4, 2, 4]), array([12,  3,  4]))

In [72]:
print(f'Манхэттенская норма вектора x1:\n{norm(x1, ord=1)}')

Манхэттенская норма вектора x1:
10.0


In [73]:
print(f'Манхэттенская норма вектора x2:\n{norm(x2, ord=1)}')

Манхэттенская норма вектора x2:
19.0


In [74]:
print(f'Евклидова норма вектора x1:\n{norm(x1, ord=2)}')

Евклидова норма вектора x1:
6.0


In [75]:
print(f'Евклидова норма вектора x2:\n{norm(x2, ord=2)}')

Евклидова норма вектора x2:
13.0


In [76]:
cos_phi = np.dot(x1, x2) / norm(x1) / norm(x2)
cos_phi

0.8974358974358974

Пересчитаем вручную:
    
    
$$cos\varphi = \frac{(x,y)}{\left \|x\right \|\cdot\left \|y\right \|}.$$

In [77]:
cos_phi_1 = (4 * 12 + 2 * 3 + 4 * 4) / (norm_ev_x1 * norm_ev_x2)
cos_phi_1

0.8974358974358975

In [78]:
print(f'Косинус угла между векторами {cos_phi:.2f}')
print(f'Угол в радианах {acos(cos_phi_1):.2f}')
print(f'Угол в градусах {(acos(cos_phi_1) * 180) / pi :.2f}')

Косинус угла между векторами 0.90
Угол в радианах 0.46
Угол в градусах 26.18


__3.__ Определите, будет ли линейное пространство евклидовым, если за скалярное произведение принять:<br>
а) произведение длин векторов;<br>
б) утроенное обычное скалярное произведение векторов?<br>

__3__ Решение:

__Определение__

Линейное пространство над полем вещественных чисел называется _евклидовым пространством_, если на нём введено правило, согласно которому каждой упорядоченной паре векторов $x$ и $y$ поставлено в соответствие вещественное число, называемое _скалярным произведением_ и обозначаемое символом $(x, y)$.

Указанное правило должно подчиняться четырём аксиомам:<br>
1) $(x,y)=(y,x).$<br>
2) $(\lambda x, y)=\lambda(x, y).$<br>
3) $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y).$<br>
4) $(x, x)\geq0$, причём $(x,x)=0\Leftrightarrow x=0.$


а) произведение длин векторов;<br>

Чаще всего длина вектора находится по Евклидовой норме.

$$\left\|x\right\|_{2} = \sqrt{\sum_{i}|x_{i}|^{2}}.$$

Проверим на соответствие правилам.
1) $(x,y)=(y,x).- соответствует$<br> 
2) $(\lambda x, y)=\lambda(x, y). - соответствует$<br>
3) $(x_{1}+x_{2},y)=(x_{1},y)+(x_{2},y). - соответствует$<br>
4) $(x, x)\geq0$, причём $(x,x)=0\Leftrightarrow x=0. - соответствует$

**Ответ**: линейное пространство будет евклидовым.

б) утроенное обычное скалярное произведение векторов?<br>

**Ответ**: линейное пространство будет евклидовым, так как тоже соответствует всем правилам.

__4.__ Выясните, какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве $\mathbb{R}^{3}$:<br>
а) $(1,0,0),(0,0,1);$ <br>
б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>
в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>
г) $(1,0,0),(0,1,0),(0,0,1)?$ 

__4.__ Решение


__Определение.__ В конечномерном евклидовом пространстве базис $\{e_{1},e_{2}...,e_{n}\}$ называется ортонормированным, если:

$(e_{i}, e_{j})=0$ $\forall$ $i\neq j$ и $(e_{i},e_{i})=1$ $\forall$ $i\in[1, n].$

а) $(1,0,0),(0,0,1);$ <br>

In [79]:
a1 = np.array([1, 0, 0])

a2 = np.array([0, 0, 1])

In [80]:
np.dot(a1, a2)

0

In [81]:
np.dot(a1, a1)

1

In [82]:
np.dot(a2, a2)

1

**Ответ**: вектора $(1,0,0),(0,0,1);$ образуют ортонормированный базис.

б) $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1);$<br>

In [83]:
b1 = np.array([1 / np.sqrt(2), - 1 / np.sqrt(2), 0])

b2 = np.array([1 / np.sqrt(2), 1 / np.sqrt(2), 0])

b3 = np.array([0, 0, 1])

In [84]:
np.dot(b1, b2)

0.0

In [85]:
np.dot(b1, b3)

0.0

In [86]:
np.dot(b2, b3)

0.0

In [87]:
print(f'{norm(b1):.1f}, {norm(b2):.1f}, {norm(b3):.1f}')

1.0, 1.0, 1.0


**Ответ**: вектора $(1/\sqrt{2},-1/\sqrt{2},0),(1/\sqrt{2},1/\sqrt{2},0), (0,0,1)$ образуют ортонормированный базис.

в) $(1/2, -1/2, 0), (0, 1/2, 1/2), (0,0,1);$<br>

In [88]:
v1 = np.array([1 / 2, - 1 / 2, 0])

v2 = np.array([0, 1 / 2, 1 / 2])

v3 = np.array([0, 0, 1])

In [89]:
np.dot(v1, v2)

-0.25

In [90]:
np.dot(v1, v3)

0.0

In [91]:
np.dot(v2, v3)

0.5

In [92]:
print(f'{norm(v1):.1f}, {norm(v2):.1f}, {norm(v3):.1f}')

0.7, 0.7, 1.0


**Ответ**: не ортогональный, не ортонормированный базис

г) $(1,0,0),(0,1,0),(0,0,1)?$ 

In [93]:
g1 = np.array([1,0,0])

g2 = np.array([0,1,0])

g3 = np.array([0,0,1])

In [94]:
np.dot(g1, g2)

0

In [95]:
np.dot(g1, g3)

0

In [96]:
np.dot(g2, g3)

0

In [97]:
print(f'{norm(g1):.1f}, {norm(g2):.1f}, {norm(g3):.1f}')

1.0, 1.0, 1.0


**Ответ**: вектора $(1,0,0),(0,1,0),(0,0,1)$ образуют ортонормированный базис.