# Урок 3

# Линейные преобразования

## Практическое задание

__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__Решение__ 

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

Векторы коэффициентов разложения векторов $g_{i}$ по базису задают столбцы матрицы линейного оператора. Тогда базисные векторы преобразуются следующим образом:

$$Ae_{1}=-1\cdot e_{1}+2\cdot e_{2},$$

$$Ae_{2}=-6 \cdot e_{1}+6 \cdot e_{2}.$$

Теперь найдём собственные значения линейного оператора, составив и решив характеристическое уравнение:

$$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(6-\lambda)+2\cdot6=0,$$

$$\lambda^{2} -5\lambda + 6 = 0,$$

$$D = 1$$

$$\lambda_{1,2} = \frac{ 5 \pm \sqrt{1}} {2}$$

$$\lambda_1 = 3$$

$$\lambda_2 = 2$$

Для $\lambda_1 = 3$

Найдём собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим:

$$\begin{cases}
-x_{1}-6x_{2}= 3 \cdot x_{1}, \\
2 \cdot x_{1}+6 \cdot x_{2}= 3 \cdot x_{2}.
\end{cases}$$ 

$$\begin{cases}
x_{1}= -\frac{3x_2}{2}, \\
x_{2}= -\frac{2x_1}{3}.
\end{cases}$$ 

__Таким образом, получается, придавая переменной y произвольные значения, получаем бесконечное множество собственных веторов, которые коллинеарны друг другу. Например, возьмем произвольные знанения, x1 = -3, тогда x2 = 2__

$$\begin{cases}
x_{1}= -3, \\
x_{2}= 2.
\end{cases}$$ 

__Ниже, с помощью модуля np.linalg.eig подобраны значения:__

$$\begin{cases}
x_{1}= 0.8321, \\
x_{2}= -0.5547.
\end{cases}$$ 



Для $\lambda_2 = 2$

Найдём собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим:

$$\begin{cases}
-x_{1}-6x_{2}= 2 \cdot x_{1}, \\
2 \cdot x_{1}+6 \cdot x_{2}= 2 \cdot x_{2}.
\end{cases}$$ 

$$\begin{cases}
x_{1}= -2{x_2}, \\
x_{2}= -\frac{x_1}{2}.
\end{cases}$$ 

__Таким образом, получается, придавая переменной y произвольные значения, получаем бесконечное множество собственных веторов, которые коллинеарны друг другу. Например, возьмем произвольные знанения, x1 = -2, тогда x2 = 1__

$$\begin{cases}
x_{1}= -2, \\
x_{2}= 1.
\end{cases}$$ 

__Ниже, с помощью модуля np.linalg.eig подобраны значения:__

$$\begin{cases}
x_{1}= -0.8944, \\
x_{2}= 0.4472.
\end{cases}$$ 



In [3]:
import numpy as np

np.set_printoptions(precision=4, suppress=True)

In [4]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.8944  0.8321]
 [ 0.4472 -0.5547]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

__Решение__ 

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Найдем собственные значения:

$$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix} = 0,$$

$$(-1-\lambda)(-1-\lambda)- 0=0,$$

$$(-1-\lambda)^2 =0,$$

$$-1-\lambda =0,$$

$$\lambda =-1,$$


Найдём собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученное собственное значение в выражение $\textbf{A}x=\lambda x$:

$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
-1
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$$

Получим:

$$\begin{cases}
-1 \cdot x_{1}+ 0 \cdot x_{2}= -1 \cdot x_{1}, \\
0 \cdot x_{1}-1 \cdot x_{2}= -1 \cdot x_{2}.
\end{cases}$$ 

$$\begin{cases}
-x_{1}= -x_{1}, \\
-x_{2}= -x_{2}.
\end{cases}$$ 

__Так как в данную систему мы можем подставить абсолютно любые значения x1 и x2, соответственно для данной системы подходит любой вектор, с любыми координатами. Таким образом, любой вектор будет считаться собственным для оператора поворота на 180 градусов, что логично, так как поворот на 180 градусов - это поворот в противоположное направление (все вектора сохраняют свое местоположение, только становятся направлены в противоположную сторону (умножаются на -1), при этом коллинеарность сохраняется).__

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.


__Решение__ 

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

вектор $x=(1,1)$ 


Предположим, что вектор $x$ считается собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором:

$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}.
$$



$$\begin{cases}
1+1=1\cdot\lambda \\ 
-1+3 = 1\cdot \lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}.$$

Такая система имеет решение 2, следовательно, вектор  $x=(1,1)$ __считается собственным вектором__ линейного оператора, заданного матрицей $A$.

In [6]:
a = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[ 1  1]
 [-1  3]]
Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.7071 -0.7071]
 [ 0.7071 -0.7071]]


**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

__Решение__ 

Предположим, что вектор $x$ считается собственным вектором заданного линейного оператора. Тогда:


$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}
$$

$$\Rightarrow
\begin{cases}
3\lambda=-9\\ 
-3\lambda=9\\
-4\lambda=-12
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=3
\end{cases}.$$

Такая система не имеет смысла, следовательно, __вектор  $x=(3, -3, -4)$ не считается собственным вектором__ линейного оператора, заданного матрицей $A$.

In [7]:
a = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(a)
 
print(f'Матрица A:\n{a}')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]
Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.7071 -0.7071  0.    ]
 [ 0.7071  0.7071  0.    ]
 [ 0.      0.      1.    ]]
