# Урок 5

# Сингулярное разложение матриц

## Практическое задание

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$

__Решение__


In [71]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [72]:
A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5], 
              [0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [73]:
U, s, W = np.linalg.svd(A)

In [74]:
U

array([[ 0.17,  0.16, -0.53, -0.8 , -0.16],
       [ 0.39, -0.53,  0.61, -0.43,  0.03],
       [-0.14, -0.82, -0.52,  0.14,  0.07],
       [ 0.89,  0.06, -0.25,  0.38, -0.06],
       [ 0.08,  0.11, -0.08, -0.11,  0.98]])

In [75]:
s

array([8.82, 6.14, 2.53])

In [76]:
W

array([[ 0.07,  0.72,  0.69],
       [-0.37,  0.67, -0.65],
       [-0.93, -0.21,  0.31]])

In [77]:
# Транспонируем матрицу W
V = W.T
V

array([[ 0.07, -0.37, -0.93],
       [ 0.72,  0.67, -0.21],
       [ 0.69, -0.65,  0.31]])

In [78]:
# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

In [79]:
print(f'Матрица D:\n{D}')

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]


In [80]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]


In [81]:
# Убедимся, что она действительно ортогональна
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [82]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0.07 -0.37 -0.93]
 [ 0.72  0.67 -0.21]
 [ 0.69 -0.65  0.31]]


In [83]:
# Убедимся, что она действительно ортогональна
print(np.dot(V.T, V))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [84]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


In [85]:
A_f = np.dot(np.dot(U, D), V.T)
A_f

array([[ 1.,  2., -0.],
       [-0.,  0.,  5.],
       [ 3., -4.,  2.],
       [ 1.,  6.,  5.],
       [ 0.,  1.,  0.]])

2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

__Решение__

    а) евклидову норму;

__Правило__

Осуществим сингулярное разложение матрицы $A=UDV^{T}$ и подставим его в выражение определения нормы, принимая во внимание, что ортогональные матрицы сохраняют скалярное произведение:

$$\left \| A \right \|_{E}^{2}=\text{max}\left (\frac{(Ax,Ax)}{(x,x)}\right )=\text{max}\left (\frac{(UDV^{T}x,UDV^{T}x)}{(V^{T}x,V^{T}x)}\right )=\text{max}\left (\frac{(Dz,Dz)}{(z,z)}\right ).$$

Таким образом, евклидова норма матрицы равна евклидовой норме диагональной матрицы из её сингулярных чисел $D$. Максимальное значение полученного отношения будет равно максимальному сингулярному числу $\mu_{max}$, и, принимая во внимание факт сортировки по убыванию сингулярных чисел, получим:

$$\left \| A \right \|_{E}=\mu_{1}.$$

In [86]:
#Получается, евклидова норма матрицы равна норме диагональной матрицы из ее сингулярных чисел D. То есть ее нулевому елементу.
D

array([[8.82, 0.  , 0.  ],
       [0.  , 6.14, 0.  ],
       [0.  , 0.  , 2.53],
       [0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  ]])

In [87]:
ev_norm = D[0, 0]
ev_norm

8.824868854820448

In [88]:
#проверка
ev_norm_check = np.linalg.norm(A, ord = 2)
ev_norm_check

8.824868854820442

    б) норму Фробениуса.

Есть также _норма Фробениуса_, определяемая как:

$$\left \| A \right \|_{F}=\sqrt{\sum_{i=1}^{m}\sum_{j=1}^{n}a_{ij}^{2}}.$$

Когда известно сингулярное разложение матрицы, её норма Фробениуса вычисляется как:

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}.$$

In [89]:
#Найдем норму Фробениуса вручную

frob_norm = 0
for i in range(np.linalg.matrix_rank(A)):
    frob_norm += (sum(D[i]) ** 2)
frob_norm = np.sqrt(frob_norm)
frob_norm

11.045361017187265

In [90]:
#Найдем с помощью numpy
frob_norm_check = np.linalg.norm(A, ord = None)
frob_norm_check

11.045361017187261

In [91]:
frob_norm_check = np.linalg.norm(A, ord = 'fro')
frob_norm_check

11.045361017187261